# Generated by Django 6.0.5 on 2026-06-04 13:21

from django.db import migrations, models, transaction


def run_save_in_batches(apps, schema_editor):
    Book = apps.get_model("book_outlet", "Book")

    BATCH_SIZE = 1000

    # 1. Fetch only IDs to maintain a minuscule memory footprint
    book_ids = list(
        Book.objects.filter(slug="").values_list("id", flat=True).order_by("id")
    )

    # 2. Slice the IDs into batches
    for i in range(0, len(book_ids), BATCH_SIZE):
        batch_ids = book_ids[i : i + BATCH_SIZE]

        # 3. Wrap each individual batch in its own atomic transaction block
        with transaction.atomic():
            # Query only the instances for this batch
            books_batch = Book.objects.filter(id__in=batch_ids)

            for book in books_batch:
                # Run your modifications
                book.slug = f"book-{book.id}"

                # Triggers custom save() overrides and signals cleanly
                book.save()


class Migration(migrations.Migration):
    dependencies = [
        ("book_outlet", "0003_book_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(default=''),
        ),
        migrations.RunPython(run_save_in_batches, migrations.RunPython.noop, elidable=True),
    ]
