# Generated by Django 6.0.6 on 2026-06-07 09:16

from django.db import migrations, models


def code(apps, schema_editor):
    Author = apps.get_model("book_outlet", "Author")
    Book = apps.get_model("book_outlet", "Book")

    for book in Book.objects.all():
        full_name = (book.author_name or "").strip()

        if not full_name:
            continue

        parts = full_name.split(maxsplit=1)

        first_name = parts[0]
        last_name = parts[1] if len(parts) > 1 else ""

        author, _ = Author.objects.get_or_create(
            first_name=first_name,
            last_name=last_name,
        )

        book.author = author
        book.save(update_fields=["author"])


def reverse_code(apps, schema_editor):
    Book = apps.get_model("book_outlet", "Book")

    for book in Book.objects.select_related("author"):
        if book.author_id:
            book.author_name = (
                f"{book.author.first_name} {book.author.last_name}".strip()
            )
            book.save(update_fields=["author_name"])


class Migration(migrations.Migration):
    dependencies = [
        ("book_outlet", "0005_alter_book_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="author_name",
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=125)),
                ("last_name", models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                to="book_outlet.author",
                on_delete=models.RESTRICT,
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(code, reverse_code),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                to="book_outlet.author",
                on_delete=models.RESTRICT,
                related_name="books",

            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author_name",
            field=models.CharField(
                max_length=255,
                blank=True,
            ),
        ),
        migrations.RemoveField(
            model_name="book",
            name="author_name",
        ),
    ]
